package toolsynth

import "time"

// ToolGap represents a detected gap where Wunderpus lacks a tool or has an inefficient one.
type ToolGap struct {
	Name               string   `json:"name"`
	Description        string   `json:"description"`
	GapType            GapType  `json:"gap_type"`            // hard, soft, efficiency
	Evidence           []string `json:"evidence"`            // episodic memory entries that demonstrate the gap
	Priority           float64  `json:"priority"`            // 0.0-1.0, higher = more urgent
	SuggestedInterface string   `json:"suggested_interface"` // LLM-suggested Go interface signature
}

// GapType classifies how the gap was detected.
type GapType string

const (
	// HardGap means the task failed because no tool existed.
	HardGap GapType = "hard"
	// SoftGap means the tool exists but is slow or produces poor results.
	SoftGap GapType = "soft"
	// EfficiencyGap means a workaround was used instead of a proper tool.
	EfficiencyGap GapType = "efficiency"
)

// ToolSpec is the specification for a synthesized tool, produced by the Designer.
type ToolSpec struct {
	Name         string      `json:"name"`
	Description  string      `json:"description"`
	GoInterface  string      `json:"go_interface"` // e.g. "func Parse(path string) (PDFContent, error)"
	Parameters   []ParamSpec `json:"parameters"`
	ReturnType   string      `json:"return_type"`
	Dependencies []string    `json:"dependencies"`
	TestCases    []TestCase  `json:"test_cases"`
	Origin       string      `json:"origin"` // "synthesized"
	CreatedAt    time.Time   `json:"created_at"`
	GapEvidence  []string    `json:"gap_evidence"` // evidence from the gap
}

// ParamSpec describes a single parameter for a synthesized tool.
type ParamSpec struct {
	Name        string `json:"name"`
	Type        string `json:"type"` // string, number, boolean, object
	Description string `json:"description"`
	Required    bool   `json:"required"`
}

// TestCase defines an input/expected pair for testing a synthesized tool.
type TestCase struct {
	Input    map[string]any `json:"input"`
	Expected string         `json:"expected"` // expected output substring or JSON
}

// ToolTestResult holds the result of testing a synthesized tool.
type ToolTestResult struct {
	AllPassed    bool     `json:"all_passed"`
	PassRate     float64  `json:"pass_rate"`
	AvgLatencyMs int64    `json:"avg_latency_ms"`
	Errors       []string `json:"errors"`
	BuildOutput  string   `json:"build_output"`
}

// GeneratedCandidate holds one candidate source code generated by the Coder.
type GeneratedCandidate struct {
	Source      string  `json:"source"`
	Temperature float64 `json:"temperature"`
	BuildError  string  `json:"build_error,omitempty"`
}

// ScanStats tracks detector run statistics.
type ScanStats struct {
	EntriesScanned int           `json:"entries_scanned"`
	GapsFound      int           `json:"gaps_found"`
	ScanDuration   time.Duration `json:"scan_duration"`
	LastScan       time.Time     `json:"last_scan"`
}

// LLMCaller abstracts LLM completion calls for the tool synthesis pipeline.
type LLMCaller interface {
	Complete(req CompletionRequest) (string, error)
}

// CompletionRequest is a simplified LLM request for tool synthesis.
type CompletionRequest struct {
	SystemPrompt string
	UserPrompt   string
	Temperature  float64
	MaxTokens    int
}

// CodeValidator abstracts Go source validation (go build, go vet).
type CodeValidator interface {
	// Validate checks if the given Go source compiles.
	// Returns build output and any error.
	Validate(source string, pkgDir string) (buildOutput string, err error)
}
