// Code generated by "stringer -type=BoxStyle -linecomment"; DO NOT EDIT.

package tui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BoxStyleRounded-0]
	_ = x[BoxStyleDouble-1]
	_ = x[BoxStyleSingle-2]
	_ = x[BoxStyleBold-3]
	_ = x[BoxStyleRound-4]
}

const _BoxStyle_name = "BoxStyleRoundedBoxStyleDoubleBoxStyleSingleBoxStyleBoldBoxStyleRound"

var _BoxStyle_index = [...]uint8{0, 15, 29, 43, 55, 68}

func (i BoxStyle) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BoxStyle_index)-1 {
		return "BoxStyle(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BoxStyle_name[_BoxStyle_index[idx]:_BoxStyle_index[idx+1]]
}
