// Code generated by "stringer -type=LogLevel -linecomment"; DO NOT EDIT.

package tui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogLevelDebug-0]
	_ = x[LogLevelInfo-1]
	_ = x[LogLevelWarn-2]
	_ = x[LogLevelError-3]
}

const _LogLevel_name = "LogLevelDebugLogLevelInfoLogLevelWarnLogLevelError"

var _LogLevel_index = [...]uint8{0, 13, 25, 37, 50}

func (i LogLevel) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LogLevel_index)-1 {
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[idx]:_LogLevel_index[idx+1]]
}
