// Code generated by "stringer -type=NotificationType -linecomment"; DO NOT EDIT.

package tui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotificationInfo-0]
	_ = x[NotificationSuccess-1]
	_ = x[NotificationWarning-2]
	_ = x[NotificationError-3]
}

const _NotificationType_name = "NotificationInfoNotificationSuccessNotificationWarningNotificationError"

var _NotificationType_index = [...]uint8{0, 16, 35, 54, 71}

func (i NotificationType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NotificationType_index)-1 {
		return "NotificationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NotificationType_name[_NotificationType_index[idx]:_NotificationType_index[idx+1]]
}
