package ags

import (
	"context"
	"fmt"
	"log/slog"
)

// RSIProposal is a lightweight representation of an RSI proposal for AGS integration.
type RSIProposal struct {
	TargetFunction string
	WeaknessScore  float64
	Reason         string
}

// WeaknessReporter is the interface the recursive loop needs from RSI.
type WeaknessReporter interface {
	Generate(codeMap interface{}) *WeaknessReportSnapshot
}

// WeaknessReportSnapshot is a lightweight snapshot for AGS integration.
type WeaknessReportSnapshot struct {
	TopCandidates []WeaknessCandidate
}

// WeaknessCandidate represents a weak function from the RSI perspective.
type WeaknessCandidate struct {
	FunctionName  string
	Score         float64
	PrimaryReason string
}

// RecursiveLoop creates the full recursive loop: RSI improves AGS which
// improves goal quality which drives better RSI targets.
type RecursiveLoop struct {
	scorer      *PriorityScorer
	store       *GoalStore
	synthesizer *GoalSynthesizer
}

// NewRecursiveLoop creates the recursive bridge between AGS and RSI.
func NewRecursiveLoop(scorer *PriorityScorer, store *GoalStore, synth *GoalSynthesizer) *RecursiveLoop {
	return &RecursiveLoop{
		scorer:      scorer,
		store:       store,
		synthesizer: synth,
	}
}

// RunAfterMetacognition runs after the metacognition loop completes.
// It checks if any AGS functions appear weak and generates RSI-aligned goals.
func (r *RecursiveLoop) RunAfterMetacognition(ctx context.Context, report *MetacognitionReport, weaknesses []WeaknessCandidate) ([]Goal, error) {
	if report == nil {
		return nil, nil
	}

	// Check if any AGS functions are in the top weakness candidates
	var rsiGoals []Goal
	for _, w := range weaknesses {
		if w.Score < 0.7 {
			continue
		}

		// Generate an RSI-aligned goal for this weak function
		goal := NewGoal(
			fmt.Sprintf("RSI: Improve %s (weakness=%.2f)", w.FunctionName, w.Score),
			fmt.Sprintf("Function %s has weakness score %.2f (reason: %s). Run RSI cycle to improve it.",
				w.FunctionName, w.Score, w.PrimaryReason),
			2, // Tier 2
			GoalImproveCapabilities.Title,
			[]string{
				fmt.Sprintf("Weakness score %.2f for %s", w.Score, w.FunctionName),
				"Generated by recursive metacognition+RSI loop",
			},
			[]string{
				fmt.Sprintf("RSI fitness score > 0.05 for %s", w.FunctionName),
				"Function weakness score decreases below 0.5",
			},
			w.Score, // expected value = current weakness (improvement potential)
		)

		goal.Priority = r.scorer.Score(goal)
		rsiGoals = append(rsiGoals, goal)
	}

	if len(rsiGoals) > 0 {
		slog.Info("ags recursive: generated RSI-aligned goals from weakness analysis",
			"count", len(rsiGoals))
	}

	return rsiGoals, nil
}

// RunAfterMetacognition adjusts scorer weights and potentially generates
// RSI proposals targeting AGS functions themselves.
func (r *RecursiveLoop) CheckAGSHealth(agsFunctions []WeaknessCandidate) []RSIProposal {
	var proposals []RSIProposal

	// AGS function names that RSI could improve
	agsTargets := map[string]bool{
		"GoalSynthesizer": true,
		"PriorityScorer":  true,
		"GoalExecutor":    true,
	}

	for _, fn := range agsFunctions {
		if agsTargets[fn.FunctionName] && fn.Score > 0.7 {
			proposals = append(proposals, RSIProposal{
				TargetFunction: fn.FunctionName,
				WeaknessScore:  fn.Score,
				Reason:         fmt.Sprintf("AGS function %s is weak (score=%.2f) — RSI should improve it", fn.FunctionName, fn.Score),
			})
		}
	}

	return proposals
}
