package rsi

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/wunderpus/wunderpus/internal/audit"
	"log/slog"
	"strings"
	"sync"
	"time"
)

// Proposal represents a candidate code improvement generated by the LLM.
type Proposal struct {
	ID             string
	Temperature    float64
	Diff           string
	TargetFunction string
	GeneratedAt    time.Time
	LLMModel       string
}

// CompletionFn is a function that calls an LLM for completion.
// Abstracted to allow mocking in tests.
type CompletionFn func(ctx context.Context, systemPrompt, userPrompt string, temperature float64) (string, error)

// ProposalEngine generates code improvement proposals for weak functions.
// It launches 3 parallel LLM calls at different temperatures to explore
// the improvement space.
type ProposalEngine struct {
	completeFn CompletionFn
	auditLog   AuditWriter
	modelName  string
}

// AuditWriter is a minimal interface for writing to the audit log.
type AuditWriter interface {
	Write(entry audit.AuditEntry) error
}

// NewProposalEngine creates a proposal engine with the given LLM completion function.
func NewProposalEngine(completeFn CompletionFn, modelName string) *ProposalEngine {
	return &ProposalEngine{
		completeFn: completeFn,
		modelName:  modelName,
	}
}

// SetAuditLog sets the audit log writer.
func (p *ProposalEngine) SetAuditLog(writer AuditWriter) {
	p.auditLog = writer
}

// Propose generates 3 candidate diffs for improving the given weak function.
// Each proposal is generated at a different temperature: 0.2, 0.5, 0.8.
func (p *ProposalEngine) Propose(ctx context.Context, entry WeaknessEntry) ([3]Proposal, error) {
	systemPrompt := `You are improving the Wunderpus AI agent codebase.

CONSTRAINTS:
- Output ONLY a valid unified diff (--- a/file, +++ b/file, @@ line ranges @@)
- Maintain all existing interface signatures
- Do not add external dependencies
- Do not modify files outside of internal/ directory
- Do not add imports that are not already in go.mod
- Improve the specific metrics provided (error rate, latency, complexity)

OUTPUT FORMAT: unified diff only, no explanation or markdown fences`

	userPrompt := fmt.Sprintf(`TARGET FUNCTION: %s
FILE: %s
LINES: %d-%d
CURRENT CODE:
%s

WEAKNESS METRICS:
- Error Rate: %.4f (%.2f%%)
- P99 Latency (normalized): %.4f
- Cyclomatic Complexity: %d (normalized: %.4f)
- Composite Weakness Score: %.4f
- Primary Issue: %s

Generate a diff that improves this function.`, entry.FunctionNode.QualifiedName,
		entry.FunctionNode.File,
		entry.FunctionNode.StartLine,
		entry.FunctionNode.EndLine,
		entry.FunctionNode.SourceCode,
		entry.ErrorRate, entry.ErrorRate*100,
		entry.NormalizedP99,
		entry.FunctionNode.CyclomaticComp, entry.NormalizedCC,
		entry.WeaknessScore,
		entry.PrimaryReason)

	temperatures := [3]float64{0.2, 0.5, 0.8}
	var proposals [3]Proposal
	var wg sync.WaitGroup
	var mu sync.Mutex

	for i, temp := range temperatures {
		wg.Add(1)
		go func(idx int, temperature float64) {
			defer wg.Done()

			// Each goroutine gets its own independent 120-second timeout
			propCtx, propCancel := context.WithTimeout(ctx, 120*time.Second)
			defer propCancel()

			slog.Debug("rsi proposer: generating candidate",
				"function", entry.FunctionNode.QualifiedName,
				"temperature", temperature,
			)

			response, err := p.completeFn(propCtx, systemPrompt, userPrompt, temperature)
			if err != nil {
				slog.Warn("rsi proposer: LLM call failed",
					"temperature", temperature,
					"error", err,
				)
				return
			}

			// Clean response: remove markdown fences if present
			diff := cleanDiffResponse(response)

			// Validate the diff
			if err := ValidateDiff(diff); err != nil {
				slog.Warn("rsi proposer: invalid diff from LLM",
					"temperature", temperature,
					"error", err,
				)
				return
			}

			mu.Lock()
			proposals[idx] = Proposal{
				ID:             fmt.Sprintf("proposal-%s-t%.1f-%d", entry.FunctionNode.Name, temperature, time.Now().UnixNano()),
				Temperature:    temperature,
				Diff:           diff,
				TargetFunction: entry.FunctionNode.QualifiedName,
				GeneratedAt:    time.Now().UTC(),
				LLMModel:       p.modelName,
			}
			mu.Unlock()

			slog.Info("rsi proposer: proposal generated",
				"function", entry.FunctionNode.QualifiedName,
				"temperature", temperature,
				"model", p.modelName,
			)
		}(i, temp)
	}
	wg.Wait()

	// Check if any proposals were generated
	validCount := 0
	for _, p := range proposals {
		if p.Diff != "" {
			validCount++
		}
	}
	if validCount == 0 {
		if p.auditLog != nil {
			_ = p.auditLog.Write(audit.AuditEntry{
				Timestamp: time.Now().UTC(),
				Subsystem: "rsi",
				EventType: audit.EventActionFailed,
				Payload:   []byte(`{"reason":"all 3 proposals failed validation"}`),
			})
		}
		return proposals, fmt.Errorf("rsi proposer: all 3 proposals failed validation for %s",
			entry.FunctionNode.QualifiedName)
	}

	if p.auditLog != nil {
		for _, prop := range proposals {
			if prop.Diff == "" {
				continue
			}
			payload, _ := json.Marshal(map[string]interface{}{
				"proposal_id": prop.ID,
				"target":      prop.TargetFunction,
				"temperature": prop.Temperature,
			})
			_ = p.auditLog.Write(audit.AuditEntry{
				Timestamp: prop.GeneratedAt,
				Subsystem: "rsi",
				EventType: audit.EventRSIProposalGenerated,
				Payload:   payload,
			})
		}
	}

	return proposals, nil
}

// ValidateDiff checks that a string is a valid unified diff targeting internal/.
func ValidateDiff(diff string) error {
	diff = strings.TrimSpace(diff)
	if diff == "" {
		return fmt.Errorf("empty diff")
	}

	lines := strings.Split(diff, "\n")

	// Must have at least a --- and +++ line
	hasMinus := false
	hasPlus := false
	for _, line := range lines {
		if strings.HasPrefix(line, "--- ") {
			hasMinus = true
		}
		if strings.HasPrefix(line, "+++ ") {
			hasPlus = true
		}
	}

	if !hasMinus || !hasPlus {
		return fmt.Errorf("missing --- or +++ header in diff")
	}

	// Check that target path is under internal/
	for _, line := range lines {
		if strings.HasPrefix(line, "+++ ") {
			path := strings.TrimPrefix(line, "+++ ")
			path = strings.TrimPrefix(path, "a/")
			path = strings.TrimPrefix(path, "b/")
			if !strings.HasPrefix(path, "internal/") {
				return fmt.Errorf("diff targets path %s outside internal/", path)
			}
		}
	}

	// Must have at least one hunk
	hasHunk := false
	for _, line := range lines {
		if strings.HasPrefix(line, "@@") {
			hasHunk = true
			break
		}
	}
	if !hasHunk {
		return fmt.Errorf("diff has no hunks (@@ markers)")
	}

	return nil
}

// cleanDiffResponse strips markdown fences and extra whitespace from LLM responses.
func cleanDiffResponse(response string) string {
	s := strings.TrimSpace(response)

	// Remove ```diff or ```go or ``` fences
	if strings.HasPrefix(s, "```") {
		lines := strings.Split(s, "\n")
		if len(lines) > 1 {
			// Remove first line (```diff)
			lines = lines[1:]
			// Remove trailing ```
			if len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "```" {
				lines = lines[:len(lines)-1]
			}
			s = strings.Join(lines, "\n")
		}
	}

	return strings.TrimSpace(s)
}
