// Code generated by "stringer -type=FailoverReason -linecomment"; DO NOT EDIT.

package provider

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FailoverReasonNone-0]
	_ = x[FailoverReasonRateLimit-1]
	_ = x[FailoverReasonTimeout-2]
	_ = x[FailoverReasonServerError-3]
	_ = x[FailoverReasonQuotaExceeded-4]
	_ = x[FailoverReasonInvalidRequest-5]
	_ = x[FailoverReasonRetriableError-6]
}

const _FailoverReason_name = "FailoverReasonNoneFailoverReasonRateLimitFailoverReasonTimeoutFailoverReasonServerErrorFailoverReasonQuotaExceededFailoverReasonInvalidRequestFailoverReasonRetriableError"

var _FailoverReason_index = [...]uint8{0, 18, 41, 62, 87, 114, 142, 170}

func (i FailoverReason) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_FailoverReason_index)-1 {
		return "FailoverReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FailoverReason_name[_FailoverReason_index[idx]:_FailoverReason_index[idx+1]]
}
